FROM nvidia/cuda:8.0-cudnn6-runtime

RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get update
RUN apt-get install -y nodejs
RUN apt-get install -y build-essential

RUN nodejs -v

RUN npm install node-wav
RUN npm install threads
RUN npm install uuid
RUN npm install deepspeech-gpu

COPY bin ./

CMD [ "node", "server.js" ]